### ISSUE TITLE
Sorry for contacting using this way.

### ISSUE THREAD

**Issue by chaiban** [karthikm-0/Pong#1]
Hello @karthikm-0 
I noticed that when you converted panda gripper to graspit format you faced an issue regarding closing/opening of fingers.

How did you clear the issue ?
Could you please share the solution ?

Once again, sorry to contacting in wrong way.

Thanks!

**Comment by karthikm-0** [comment]
Hey, 

Sorry, I haven't replied, things have been a bit busy. 

Regarding graspit, I never managed to figure out how to correct it. I think I ended up using a different grasping library in the end. I believe it is this one: https://ros-planning.github.io/moveit_tutorials/doc/moveit_grasps/moveit_grasps_tutorial.html

**Comment by chaiban** [comment]
Okay Thank you for the information.
